"""empty message

Revision ID: 0d1a6aee989f
Revises: 733477d1fdd7
Create Date: 2023-11-24 15:34:50.683002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1a6aee989f'
down_revision = '733477d1fdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Setup', schema=None) as batch_op:
        batch_op.drop_column('other')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
