"""empty message

Revision ID: 149a8a81f9ab
Revises: 371afe8b768e
Create Date: 2024-04-28 15:37:38.184936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149a8a81f9ab'
down_revision = '371afe8b768e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('scanLogPath')
    with op.batch_alter_table('USBlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_id', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('USBlog_logPath_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('USBlog_device_id_fkey', type_='foreignkey')
        batch_op.drop_column('logPath_id')
        batch_op.drop_column('device_id')
    op.drop_table('scanLogPath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USBlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logPath_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('USBlog_device_id_fkey', 'devices', ['device_id'], ['id'])
        batch_op.create_foreign_key('USBlog_logPath_id_fkey', 'scanLogPath', ['logPath_id'], ['id'])
        batch_op.drop_column('scan_id')

    op.create_table('scanLogPath',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"scanLogPath_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('clamav', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('oleid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('yara', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scanLogPath_pkey'),
    sa.UniqueConstraint('id', name='scanLogPath_id_key')
    )
    # ### end Alembic commands ###
