"""empty message

Revision ID: 1fc0bd4a0e58
Revises: bcb863b128e4
Create Date: 2024-02-20 11:21:56.361408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc0bd4a0e58'
down_revision = 'bcb863b128e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extensions_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension', sa.String(length=8), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extensions_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.drop_column('extension')

    # ### end Alembic commands ###
