"""empty message

Revision ID: 2835b245b292
Revises: 71d6ace85b8a
Create Date: 2023-11-26 21:48:19.121492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2835b245b292'
down_revision = '71d6ace85b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Devices', schema=None) as batch_op:
        batch_op.drop_column('enable')

    # ### end Alembic commands ###
