"""empty message

Revision ID: 4c7f708bfd14
Revises: 1fc0bd4a0e58
Create Date: 2024-02-20 15:58:37.121188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7f708bfd14'
down_revision = '1fc0bd4a0e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extensions_file', schema=None) as batch_op:
        batch_op.alter_column('mimetype',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extensions_file', schema=None) as batch_op:
        batch_op.alter_column('mimetype',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
