"""empty message

Revision ID: 5f2cc934ed82
Revises: dab1a35bd90a
Create Date: 2023-12-06 10:05:21.744134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2cc934ed82'
down_revision = 'dab1a35bd90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Metrics', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
