"""empty message

Revision ID: 733477d1fdd7
Revises: 
Create Date: 2023-11-24 14:15:02.852980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733477d1fdd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Setup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Setup', schema=None) as batch_op:
        batch_op.drop_column('other')

    # ### end Alembic commands ###
