"""empty message

Revision ID: d1adc1c50b43
Revises: 9d1f29eabf45
Create Date: 2024-03-21 12:20:17.863538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1adc1c50b43'
down_revision = '9d1f29eabf45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codeep', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.DateTime(timezone=True),
               nullable=False,postgresql_using="timestamp::timestamp with time zone")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codeep', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
