"""empty message

Revision ID: ea0a4844f545
Revises: 078ebf820ab2
Create Date: 2024-03-21 14:26:15.959788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea0a4844f545'
down_revision = '078ebf820ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codeep')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_codeEP_fkey', type_='foreignkey')
        batch_op.drop_column('codeEP')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codeEP', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_codeEP_fkey', 'codeep', ['codeEP'], ['id'])

    op.create_table('codeep',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='codeep_pkey'),
    sa.UniqueConstraint('id', name='codeep_id_key')
    )
    # ### end Alembic commands ###
