/*
Generated by Yara-Rules
On 27-04-2024
*/
include "./ransomware/Avaddon.yar"
include "./ransomware/BlackKingDom.yar"
include "./ransomware/CryLock.yar"
include "./ransomware/Darkside.yar"
include "./ransomware/DearCry.yar"
include "./ransomware/Ekans.yar"
include "./ransomware/Fusion.yar"
include "./ransomware/Pysa.yar"
include "./ransomware/RagnarLocker.yar"
include "./ransomware/REvil_Cert.yar"
include "./ransomware/REvil_Dropper.yar"
include "./ransomware/Satan_Mutexes.yar"
include "./ransomware/Sfile.yar"
include "./ransomware/WhiteBlack.yar"
include "./ransomware/WickrMe.yar"
include "./ransomware/WinLock.yar"
include "./ransomware/XiaoBa.yar"
include "./ransomware/Zeppelin.yar"
